common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use frontend\models\Account;
use frontend\models\Member;


/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property integer $superadmin
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['username', 'string'],
            ['email', 'email'],
            ['superadmin', 'integer'],
            ['status', 'default', 'value' => self::STATUS_DELETED],
            
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['username', 'email'], 'required']
            
        ];
    }

    /**
     * Retourne objet User pour un utilisateur Activé
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }
    
    
    /**
     * Retourne objet User pour un utilisateur activé et non activé
     */
    public static function findId($id)
    {
        return static::findOne(['id' => $id]);
    }
    
    public static function getAll()
    {
        return static::find()->all();
    }
    

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
    
    
    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }
    
    /**
     * Trouve un User en fonction de sa clé d'authentification
     * Utilisé pour confirmer l'e-mail
     * @param String $auth_key
     * @return User
     */
    public static function findByAuthKey($auth_key)
    {
        return static::findOne(['auth_key' => $auth_key]);
    }


    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }
    
    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }
    
    /**
     * Passe le statut d'un User à 10
     * @return boolean 
     */
    public function setActive()
    {
        $this->status = self::STATUS_ACTIVE;
        
        if($this->save()) {
            return true;
        }
        
        return false;
    }


    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    
    
    public function findMember()
    {
        return $this->hasOne(Member::classname(), ['user_id' => 'id'])->one();
    }
    
    public function findAccount()
    {
        return $this->hasOne(Account::classname(), ['user_id' => 'id'])->one();
    }
    
    public function updateUser($user)
    {
        var_dump($this, $user);die;
        
        
        
        if($this->save()) {
            return true;
        }
        
        return false;
    }
    
   
    
    

}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\User;

class UserController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    
    public function actionList()
    {
        $users = User::getAll();
        
        foreach ($users as $k => $v) {
            if($v->id) {
                $account[] = $v->findAccount();
            }
        }
        

        return $this->render('list', [
            'users' => $users,
        ]);
        
        
    }
    
    
    /* Non utilisée : lien vers profil en frontend
    public function actionProfile($id_user)
    {
        $user = User::findIdentity($id_user);
        
        
        //Dans l'idéal redirige vers la page profil du front -- Ne marche pas
        return $this->renderPartial('@frontend/user/profile', [
            'user' => $user
        ]);
    }
     * 
     */
    
    
    public function actionDisable($id_user)
    {
        $current = Yii::$app->user->identity;
        $user = User::findId($id_user);
        
        if($user->status === 10) {
            $user->status = 0;
        } elseif ($user->status === 0) {
            $user->status = 10;
        } else {
            var_dump($user->status);die;
            return false;
        }
        
        if($user->save()) {
            
            //Gérer le cas où l'User désactivé est l'user courant : ajouter confirm en JS sur vue + redirect sur Login
            if(!Yii::$app->user->identity) {
                return $this->redirect(['/site/login']);
            }
            
            return $this->redirect(['list']);
        }
    }
    
    
    public function actionUpdate($id_user)
    {
        
        $model = new User;
        
        $user = User::findId($id_user);
        
        
        if($user->load(Yii::$app->request->post()) && $user->validate()) {
            
            if($user->save()) {
                Yii::$app->getSession()->setFlash('success', 'Modification réussie');
                return $this->redirect(['list']);
            }   

        }
        
        return $this->renderAjax('update', [
            'user' => $user,
            'model' => $model
        ]);
    }

}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;
use common\models\LoginForm;
use common\models\UploadForm;
use frontend\models\ContactForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use frontend\models\Member;
use frontend\models\Account;
use common\models\User;
use frontend\models\UpdateUserForm;
use yii\web\UploadedFile;
use common\models\UploadFile;

class UserController extends \yii\web\Controller
{
    public function actionIndex($username = null)
    {
        if($username === NULL) {
            $user = Yii::$app->user->identity;
        }
        else {
            $user = User::findByUsername($username);
        }
        
        $accountUser = $user->findAccount();
        
        $avatar = $accountUser->getAvatar();
        
        $memberUser = $user->findMember();        
        //var_dump($accountUser, $memberUser); die;
        
        
        return $this->render('index', [
            'user' => $user,
            'account' => $accountUser,
            'member' => $memberUser,
            'avatar' => $avatar
        ]);
    }
    
    
    /**
     * Modifie les informations d'identification de l'User en cours, ou de l'User $id_user
     * @param int $id_user
     * @return type
     */
    public function actionUpdateLogs($id_user = null)
    {
        $model = new UpdateUserForm;
        
        if($id_user) {
            $user = User::findIdentity($id_user);
        } 
        else {
            $user = Yii::$app->user->identity;
        }
        
        
        if($model->load(Yii::$app->request->post()) && $model->validate()){
            
            if($model->updateLogs($user)){
                
                Yii::$app->getSession()->setFlash(
                    'success','Modification réussie'
                );

                return $this->redirect(['index']);
            }
        }
        else {
            return $this->render('update-user', [
                'model' => $model,
                'user' => $user
            ]);
        }
        
    }
    
    public function actionUpdateAccount($id_user = null)
    {
        $model = new Account;
        
        if($id_user) {
            $account = User::findIdentity($id_user)->findAccount();
            //var_dump($user->username);die;
        } else {
            $account = Yii::$app->user->identity->findAccount();

            if(Yii::$app->session->get('account') == null){
                Yii::$app->session->set('account', Yii::$app->user->findAccount()); 
            }
        }    
       
        if($model->load(Yii::$app->request->post() && $model->validate())) {
            
        }
        else {
            return $this->render('update-account', [
                'model' => $model,
                'account' => $account
            ]);
        }
        
    }
    
    
    public function actionNewsletter($sub)
    {
        if($sub == 1) {
            var_dump('Subscribe newsletter');
        }
        elseif($sub == 0) {
            var_dump('Unsubscribe newsletter');
        }
        else {
            return false;
        }

    }
    
    /**
     * 
     */
    public function actionChangeAvatar($id_user = null)
    {
        $model = new UploadForm;        
        
        //Récupération du dossier frontend/web/uploads/sha1(login)/
        if($id_user == NULL) {
            $user = Yii::$app->user->identity;
            
        } else {
            $user = User::findIdentity($id_user);    
        }
        
        $accountUser = $user->findAccount();

        
        if($accountUser->getAvatar() != NULL) {
            $avatar = UploadFile::findIdentity($accountUser->avatar);
        }
        else {
            $avatar = NULL;
        }

        //var_dump($avatar);die;
        if (Yii::$app->request->isPost) {

            //Chemin du dossier upload de l'User
            $hash = sha1($user->username);
            $path = 'uploads/'.$hash;                                   
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            
            if ($id = $model->uploadAvatar($path)) {
                
                //Association user
                $accountUser->updateAvatar($id);
              
                // file is uploaded successfully
                Yii::$app->getSession()->setFlash(
                    'success','Avatar changé'
                );                
                return $this->redirect(['index']);
            }
            else {
                echo "Echec de l'upload";
            }
        }

        return $this->renderAjax('change-avatar', [
            'model' => $model,
            'user' => $user,
            'avatar' => $avatar
                ]);
    }
    
    
    /**
     * Changement de l'avatar de l'utilisateur COURANT
     * @param String $type
     */
    public function actionSwitchAvatar() {
        
        if(Yii::$app->request->isPost && Yii::$app->request->post('t')) {
            if(Yii::$app->session->get('account')) {
                $account = Yii::$app->session->get('account');
            } else {
                $user = Yii::$app->user->identity;
                $account = $user->findAccount();
            }
            
            switch (Yii::$app->request->post('t')) {
                case 'avatar-default':
                    $type = 0;

                    break;
                case 'avatar-perso':
                    $type = 1;

                    break;
                case 'gravatar':
                    $type = 2;

                    break;

            }
            
            if($account->switchAvatar($type)) {
                return $account->getAvatar();
            }
           
            
        }
        
        return false;
        
        
        
        
    }

}

frontend/views/user/_update-account.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model frontend\models\Account */
/* @var $form ActiveForm */


?>
<div class="user-_update-account">

    <?php $form = ActiveForm::begin(); ?>

       
        <!-- Voir pour champ Age virtuel // Style Steam ? // Champ text ? // DropDown ? // DatePicker ? -->
        <?= $form->field($model, 'age')->textInput(['value' => $account->age]) ?>
        <?= $form->field($model, 'favorite_category') ?>
        <?= $form->field($model, 'newsletter') ?>
        <?= $form->field($model, 'past') ?>
        <?= $form->field($model, 'present') ?>
        <?= $form->field($model, 'future') ?>
        <?= $form->field($model, 'why_register') ?>
        <?= $form->field($model, 'skills') ?>
        <?= $form->field($model, 'interests') ?>
        <?= $form->field($model, 'other') ?>
        <?= $form->field($model, 'sex') ?>
    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- user-_update-account -->

frontend/views/user/_update-user.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

// get the cookie collection (yii\web\CookieCollection) from the "request" component
$account = Yii::$app->session->get('account');

/* @var $this yii\web\View */
$this->title = 'Modification des identifiants';
$this->params['breadcrumbs'][] = ['label' => $user->username.' - Profil'];
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model frontend\models\UpdateLogsForm */
/* @var $form ActiveForm */
?>
<div class="user-update-logs">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'username')->textInput(['value' => $user->username])->label('Login') ?>
        <?= $form->field($model, 'email')->textInput(['value' => $user->email])->label('E-mail') ?>
        <?= $form->field($model, 'password')->passwordInput()->label('Nouveau mot de passe') ?>
        <?= $form->field($model, 'password_repeat')->passwordInput()->label('Confirmer mot de passe') ?>
    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- user-update-logs -->

frontend/views/user/change-avatar.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\UploadForm */
/* @var $form ActiveForm */



$pathBaseAvatar = '/uploads/'.sha1('base').'/avatar.jpg';

if($avatar) {
    $pathAvatar = '/uploads/'.sha1($user->username).'/'.$avatar->filename;
}

$gravatar_path = 'https://www.gravatar.com/avatar/'.md5(strtolower(trim($user->email))).'?d=identicon&s=200&r=G';

?>
<!-- tools-upload -->

<div style="display: block;" class="popup profile-picture-popup">
    <h2>Change ton avatar</h2>
        <hr>
        <a class="avatar-change" id="avatar-default">
            <?= Html::img($pathBaseAvatar, ['label'=>'Image', 'format'=>'raw']) ?>
            <span class="avatar-description">Avatar par défaut</span>
            <span class="badge-earned-check"></span>
        </a>  
        
        <?php if($avatar): ?>
        
        <hr>
        <a class="avatar-change" id="avatar-perso">
            <?= Html::img($pathAvatar, ['label'=>'Image', 'format'=>'raw']) ?>
            <span class="avatar-description">Avatar du site</span>
            <span class="badge-earned-check"></span>
        </a>
        
        <?php endif; ?>
        
        <hr>
        <a class="avatar-change" id="gravatar">
            <?= Html::img($gravatar_path, ['label'=>'Image', 'format'=>'raw']) ?>            
            <span class="avatar-description">Gravatar</span>
            <span class="badge-earned-check"></span>
        </a>
        <hr>
        <div class="tools-upload">

            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

                <?= $form->field($model, 'imageFile')->fileInput() ?>

                <?= Html::submitButton('Upload', ['class' => 'btn btn-primary', 'id' => 'avatar-upload']) ?>
                <?php ActiveForm::end(); ?>
        </div>
        <div class="modal-footer">
            <a id="profile-picture-validate" href="#" class="btn btn-primary">Valider</a> 
            <a id="profile-picture-cancel" href="#" class="btn btn-primary">Retour</a>    
        </div>


    
</div>
<?php
    $this->registerJs("
    //Changement de l'avatar actif -- OK
    $('.avatar-change').click(function() {
        var e = $(this);
        var d = $(this).children('.avatar-description');
        
        $('.active').children('.avatar-description').removeAttr('style');            
        $('.active').removeClass('active');
        e.addClass('active');
        d.css('font-size', '20px');


        
    });
    
    //AJAX quand on quitte le modal
    $('#profile-picture-validate').click(function(){
    
        var t = $('.active').attr('id');   
        var img = $('#img-avatar');
        console.log(t);
        $.ajax({
            url : 'index.php?r=user/switch-avatar',
            method: 'POST',
            data : { t: t }
        })
        .done(function(data){        
            //Changement de l'avatar -> pas très optimal
            console.log(data);
            img.attr('src', data);
            $('#modal').modal('hide');
            
        })
        .fail(function(){
            console.log('AJAX fail');
        });

    });
    
    $('#profile-picture-cancel').on('click', function(){
        console.log('go');
        $('#modal').modal('hide');
       
    })
    
    

    ",\yii\web\View::POS_READY); 
?>

frontend/views/user/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use common\rbac\OwnRule;

/* @var $this yii\web\View */
$this->title = 'Echos-Libres - Profil de '.$user->username;
$this->params['breadcrumbs'][] = $this->title;



?>


<div id="header-profil">
    <div class="" style="float:left;">
        <h1>Profil : <?= $user->username ?></h1>
        <ul>
            <li>Inscrit sur le site depuis le <?= Yii::$app->formatter->asDate($user->created_at); ?> </li>
            
           
            <?php if($member && $member->paid === 1): ?>
            <li>Membre de l'asso depuis le <?= Yii::$app->formatter->asDate($member->adhesion); ?> </li>
            <?php endif; ?>
            
        </ul>
    </div>
    
    <?php if(Yii::$app->user->getId() === $user->id): ?>
    <div id="userSiteAttributes">
        <ul class="" style="display:inline;">            
            <li>Email : <?= $user->email ?></li>
            <li>Password : ********</li>           
            <li><a href="<?= Url::to(['user/update-logs']) ?>">Modifier</a>
        </ul>
    </div>
    <?php endif; ?>
    
</div>

<div class="core-profil">
    
    <!-- Créer une règle pour que l'admin et l'utilisateur seuls puissent modifier le profil -->
    <?php if(Yii::$app->user->getId() === $user->id): ?>
    <a href="<?= Url::to(['user/update-account']) ?>">Modifier le profil</a>
    <?php endif; ?>
    
    <div id="avatar">

        <?= Html::img($avatar, ['id' => 'img-avatar', 'label'=>'Image', 'format'=>'raw']) ?>
        
        <?php if(Yii::$app->user->getId() === $user->id): ?>
        <button value="<?= Url::to(['user/change-avatar']) ?>" class="btn btn-primary" id="change-avatar">Ajouter un avatar <br> (compatible Gravatar)</a>
        <?php endif; ?>
    </div>
    

    <!-- Popup en JS pour changer l'avatar -->
    <?php
    
        Modal::begin([
            'id' => 'modal',
            
        ]);

        echo '<div id="picture-popup"></div>';

        Modal::end();
    
    ?>

    

    <div id="userAttributes" class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>En savoir plus sur toi</th>
                </tr>
            </thead>
            <tbody>
                <?php if($account->age): ?>
                <tr>
                    <td>Age virtuel</td>
                    <td><?= $account->age ?></td>
                </tr>
                <?php endif; ?>
                
                <?php if($account->sex): ?>                
                <tr>
                    <td>Sexe</td>
                    <td><?= $account->sex ?></td>                
                </tr>
                <?php endif; ?>
                
                <?php if($account->why_register): ?>                
                <tr>
                    <td>Pourquoi t'inscrire sur Echos-Libres.fr ?</td>
                    <td><?= $account->why_register ?></td>                
                </tr> 
                <?php endif; ?>
                
                <?php if($account->skills): ?>                
                <tr>
                    <td>Savoir / Compétences à partager</td>
                    <td><?= $account->skills ?></td>                
                </tr>
                <?php endif; ?>
                
                <?php if($account->interests): ?>                
                <tr>
                    <td>Centres d'intérêt</td>
                    <td><?= $account->interests ?></td>                
                </tr>
                <?php endif; ?>
                
            </tbody>
        </table>    
    </div>

    <div id="userExpression" class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Expression libre</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Passé</td>
                    <td><?= $account->past ?></td>
                </tr>
                <tr>
                    <td>Présent</td>
                    <td><?= $account->present ?></td>                
                </tr>
                <tr>
                    <td>Futur</td>
                    <td><?= $account->future ?></td>                
                </tr>            
            </tbody>
        </table>    
    </div>
</div>


<div id="userOther" class="">
    
    <?php if($account->newsletter): ?>
        <span>Newsletter : <i>Inscrit</i></span>
        <span class="btn"><a href="<?= Url::to(['user/newsletter', 'sub' => 0]) ?>">Désinscription</a></span>
    <?php else: ?>
        <span>Newsletter : <i>Non-inscrit</i></span>
        <span class="btn"><a href="<?= Url::to(['user/newsletter', 'sub' => 1]) ?>">Inscription</a></span>
    <?php endif; ?>
        
</div>

frontend/views/user/update-account.php
<?php 

use yii\helpers\Html;
?>

<h1>Modifier profil</h1>

<?= $this->render('_update-account', array('model'=>$model , 'account' => $account)); ?>

frontend/views/user/update-user.php
<?php 

use yii\helpers\Html;
?>

<h1>Modifier identifiants</h1>

<?= $this->render('_update-user', array('model'=>$model , 'user' => $user)); ?>